name: Release

on:
  workflow_dispatch:
  push:
    paths:
      - 'static'
      - 'templates'
      - 'Dockerfile'
      - '**.go'

jobs:
  build_and_push:
    name: "Build and push Docker image to Artifact Registry"
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - id: checkout
        uses: actions/checkout@v2

      # - name: Run linter
      #   uses: golangci/golangci-lint-action@v3
      #   with:
      #     version: v1.54

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.PROVIDER_ID }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          access_token_lifetime: 5m

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ vars.ARTIFACT_REGISTRY }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and push
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          docker build -t ${{ vars.ARTIFACT_REGISTRY }}/rattz-xyz/app-repository/rattz-xyz:$COMMIT_HASH -t ${{ vars.ARTIFACT_REGISTRY }}/rattz-xyz/app-repository/rattz-xyz:latest .
          docker push ${{ vars.ARTIFACT_REGISTRY }}/rattz-xyz/app-repository/rattz-xyz --all-tags
